---
title: "HA assignment"
output: pdf_document
date: "2025-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
setwd("~/Desktop")  
nhis_00014 <- read_csv("nhis_00014.csv")  
```

## Smoking Duration data processing

```{r cars}
df <- nhis_00014 %>%
  mutate(SMOKESTATUS2 = as.numeric(SMOKESTATUS2)) # Convert SMOKESTATUS2 to numeric type for proper filtering

# Keep only current smokers (SMOKESTATUS2 is 10, 11, 12, 13)
data_smokers <- df %>%
  filter(SMOKESTATUS2 %in% c(10, 11, 12, 13)) %>%  
  mutate(
    # calculate Smoking Duration
    smoking_duration = AGE - SMOKAGEREG
  ) %>%
  # Ensure smoking duration is not negative (excluding outliers)
  filter(smoking_duration >= 0)
```
## Family lung cancer data processing
```{r cars}
# filter siltable years
data_family <- data_smokers %>%
  filter(YEAR %in% c(2000, 2005, 2010)) %>%  
  mutate(
    # Generate a family history of lung cancer variable: set to 1 if any family member has had lung cancer, set to 0 otherwise
    family_lung_cancer = ifelse(
      BMLGCAN == 1 | BFLGCAN == 1 | FBLGCAN == 1 | FSLGCAN == 1 | BDLGCAN == 1 | BSLGCAN == 1, 1, 0
    )
  )
```

## CNLUNG data processing
```{r}
# Filter out the lines where CNLUNG is empty and ensure that CNLUNG only has 0 and 1
df_filtered <- data_family %>% 
  filter(!is.na(data_family$CNLUNG) & !is.na(data_family$SMOKAGEREG) & data_family$CNLUNG %in% c(0, 1))
```

##Descriptive statistics of variables
```{r}
table(df_filtered$CNLUNG)
# Calculate and display the proportion of each category in CNLUNG
prop.table(table(df_filtered$CNLUNG))

df_filtered %>%
  summarise(
    # Calculate the mean of smoking_duration
    Mean_smoking_duration = mean(smoking_duration, na.rm = TRUE),
    # Calculate the standard deviation of smoking_duration
    SD_smoking_duration = sd(smoking_duration, na.rm = TRUE),
    # Calculate the minimum/Maximum value of smoking_duration
    Min_smoking_duration = min(smoking_duration, na.rm = TRUE),
    Max_smoking_duration = max(smoking_duration, na.rm = TRUE)
  )

# Calculate and display the proportion of each category in SEX
table(df_filtered$SEX)
prop.table(table(df_filtered$SEX)) 
# Calculate and display the proportion of each category in family_lung_cancer
table(df_filtered$family_lung_cancer)
prop.table(table(df_filtered$family_lung_cancer))
# Calculate and display the proportion of each category in EARNIMP1 
table(df_filtered$EARNIMP1)
prop.table(table(df_filtered$EARNIMP1))

```

## logistic model
```{r}
#Fit model
sex <- df_filtered$SEX
income <- df_filtered$EARNIMP1

logit_model_sd <- glm(CNLUNG ~ smoking_duration + sex + income + family_lung_cancer, 
                   data = df_filtered, family = binomial(link="logit"))
summary(logit_model_sd) #Check output 
# Draw figure of ROC
probabilities <- predict(logit_model_sd, type = "response")  #Get predict probabilities
roc_curve <- roc(df_filtered$CNLUNG, probabilities)  #Create the ROC curve object
plot(roc_curve, main = "ROC Curve", col = "black", lwd = 2)  #Draw ROC curve
# Test multi-collinearity
install.packages("car")  
library(car)
vif(logit_model_sd, data=df_filtered)

library(sandwich)  # Calculated robust standard error
library(lmtest)    # Carry out coefficient test

# Calculated robust standard error
robust_se <- vcovHC(logit_model_sd, type = "HC1")  
coeftest(logit_model_sd, vcov. = robust_se)  
```
## Robustness check
```{r cars}
## Fit model without income
logit_model_no_income <- glm(CNLUNG ~ smoking_duration + sex + family_lung_cancer,
                             data = df_filtered, family = binomial)
summary(logit_model_no_income)
## Fit model with age
age<- df_filtered$AGE
logit_model_with_age <- glm(CNLUNG ~ smoking_duration + sex + income + family_lung_cancer + age,
                            data = df_filtered, family = binomial)
summary(logit_model_with_age)
```
##Heterogeneity Analysis
```{r}
# Create a new variable `income` in df_filtered by copying values from `EARNIMP1`
df_filtered$income <- df_filtered$EARNIMP1
# Fit a logistic regression model for male participants (sex == 1)
logit_model_male <- glm(CNLUNG ~ smoking_duration + income + family_lung_cancer, 
                        data = subset(df_filtered, sex == 1), family = binomial(link="logit"))
# Fit a logistic regression model for female participants (sex == 2)
logit_model_female <- glm(CNLUNG ~ smoking_duration + income + family_lung_cancer, 
                          data = subset(df_filtered, sex == 2), family = binomial(link="logit"))
# Display the summary of the logistic regression model
summary(logit_model_male)
summary(logit_model_female)

##interaction
logit_model_interaction <- glm(CNLUNG ~ smoking_duration * sex + income + family_lung_cancer, 
                               data = df_filtered, family = binomial(link="logit"))
summary(logit_model_interaction)

```

